name: hid
version: 0.1
synopsis: Haskell in Depth" book walkthrough
description: Haskell in Depth" book walkthrough
category: Code for studuing
license: BSD3
author: barbedwire
maintainer: Vitaly Bragilevsky <vit.bragilevsky@gmail.com>
github: bravit/hid-examples
extra-source-files:
    - ChangeLog.md
    - LICENSE
    - README.md
    - stack.yaml
    - package.yaml

data-files:
    - texts/*.*

tested-with: GHC == 8.2.2, GHC == 8.4.3

dependencies: base >=4.10 && <4.13

executables:
    # Chapter 2
    locator:
        main: locator.hs
    vocab1:
        main: vocab1.hs
        dependencies: text >=1.2 && <1.3
    vocab2:
        main: vocab2.hs
        dependencies: text >=1.2 && <1.3
    vocab3:
        main: vocab3.hs
        dependencies: text >=1.2 && <1.3
    showexpr:
        main: expr/showexpr.hs
        dependencies: hint >=0.7 && <0.10

# Chapter 3
    stockquotes:
        source-dirs: stockquotes
        main: Main.hs
        other-extensions:
          - OverloadedStrings
        dependencies:
          - text >=1.2 && <1.3